<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JACK-PC" failures="0" tests="9" name="test.TestFavoriteDAO" time="5.016" errors="1" timestamp="2022-03-27T22:40:04 ICT" skipped="0">
  <testcase classname="test.TestFavoriteDAO" name="testDelete1" time="3.059"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testUpdate1" time="0.205"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testInsert1" time="0.422"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testUpdate3" time="0.158"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testInsert2" time="0.210">
    <error message="
Method TestFavoriteDAO.testInsert2()[pri:0, instance:test.TestFavoriteDAO@3012646b] should have thrown an exception of type class javax.persistence.RollbackException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method TestFavoriteDAO.testInsert2()[pri:0, instance:test.TestFavoriteDAO@3012646b] should have thrown an exception of type class javax.persistence.RollbackException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:853)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:714)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testInsert2 -->
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testDelete3" time="0.288"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testInsert3" time="0.194"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testUpdate2" time="0.168"/>
  <system-out/>
  <testcase classname="test.TestFavoriteDAO" name="testDelete2" time="0.312"/>
  <system-out/>
</testsuite> <!-- test.TestFavoriteDAO -->
